//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteFinder.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class QuoteFinderUserPrompts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal QuoteFinderUserPrompts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuoteFinder.Resources.QuoteFinderUserPrompts", typeof(QuoteFinderUserPrompts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many pages of data would you like to check?.
        /// </summary>
        public static string AskForPageCountPrompt {
            get {
                return ResourceManager.GetString("AskForPageCountPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shall process pages in parallel? [y/n].
        /// </summary>
        public static string AskForParallelExecutionChoicePrompt {
            get {
                return ResourceManager.GetString("AskForParallelExecutionChoicePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many quotes per page?.
        /// </summary>
        public static string AskForQuotesCountPrompt {
            get {
                return ResourceManager.GetString("AskForQuotesCountPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What word would you like to search for?.
        /// </summary>
        public static string AskForWordPrompt {
            get {
                return ResourceManager.GetString("AskForWordPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input. Please enter a positive number..
        /// </summary>
        public static string InvalidPageCountMessage {
            get {
                return ResourceManager.GetString("InvalidPageCountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input. Please enter &apos;y&apos; or &apos;n&apos;..
        /// </summary>
        public static string InvalidParallelExecutionChoiceMessage {
            get {
                return ResourceManager.GetString("InvalidParallelExecutionChoiceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input. Please enter a positive number..
        /// </summary>
        public static string InvalidQuotesCountMessage {
            get {
                return ResourceManager.GetString("InvalidQuotesCountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input. Please enter a single word without spaces, numbers, or special characters..
        /// </summary>
        public static string InvalidWordMessage {
            get {
                return ResourceManager.GetString("InvalidWordMessage", resourceCulture);
            }
        }
    }
}
